https://drive.google.com/drive/folders/1E6AxiyPXiEd8kzJGG1XFUp9PrMnyFj1Y?usp=sharing 

In [84]:
import numpy as np

## 1. Inisialisasi Bobot & Bias

In [ ]:
# Bobot Hidden Layer 1  (3 neuron <- 2 input)
weight_hidden1 = np.array([[ 2,  1],
                           [-1, -2],
                           [ 1, -1]], dtype=float)

# Bobot Hidden Layer 2  (2 neuron <- 3 neuron)
weight_hidden2 = np.array([[1, -2,  2],
                           [3, 1,-2]], dtype=float)

# Bobot Output Layer  (1 neuron <- 2 neuron)   
weight_output = np.array([[-2,3]], dtype=float)

# Bias
bias_hidden1 = np.array([[1],[1],[1]], dtype=float)
bias_hidden2 = np.array([[1],[1]], dtype=float)
bias_output = np.array([[1]], dtype=float)

# Hyperparameter
learning_rate = 0.01

# Data Training   
X_data1 = np.array([[1], [-2]], dtype=float) 
y_data1 = 1.0

X_data2 = np.array([[-1], [1]], dtype=float)  
y_data2 = 4.0

print("Parameter berhasil diinisialisasi.")
print(f"  weight_hidden1 shape : {weight_hidden1.shape}")
print(f"  weight_hidden2 shape : {weight_hidden2.shape}")
print(f"  weight_output  shape : {weight_output.shape}")

Parameter berhasil diinisialisasi.
  weight_hidden1 shape : (3, 2)
  weight_hidden2 shape : (2, 3)
  weight_output  shape : (1, 2)


## 2. Fungsi Aktivasi (ReLU & ReLU')

In [86]:
def relu(z):
    return np.maximum(0, z)

def relu_derivative(z):
    return (z > 0).astype(float)

## 3. Forward Pass

In [ ]:
def forward_pass(X,weight_h1,bias_h1,weight_h2,bias_h2,weight_out,bias_out):
    # Hidden Layer 1
    Z_h1 = weight_h1 @ X + bias_h1          
    A_h1 = relu(Z_h1)                        

    # Hidden Layer 2
    Z_h2 = weight_h2 @ A_h1 + bias_h2       
    A_h2 = relu(Z_h2)                       

    # Output Layer (aktivasi linear)
    Z_out  = weight_out @ A_h2 + bias_out   
    y_pred = Z_out[0, 0]                    

    return Z_h1, A_h1, Z_h2, A_h2, Z_out, y_pred

## 4. Backward Pass

In [88]:
def backward_pass(X, y_true,weight_h2, weight_out,Z_h1, A_h1, Z_h2, A_h2,y_pred):
    # Output Layer               
    delta_output = y_pred - y_true                          
    grad_weight_output = delta_output * A_h2.T              
    grad_bias_output   = delta_output                       

    # Hidden Layer 2               
    delta_hidden2 = (weight_out.T * delta_output) * relu_derivative(Z_h2)  
    grad_weight_hidden2 = delta_hidden2 @ A_h1.T            
    grad_bias_hidden2   = delta_hidden2.copy()              

    # Hidden Layer 1                                         
    delta_hidden1 = (weight_h2.T @ delta_hidden2) * relu_derivative(Z_h1)  
    grad_weight_hidden1 = delta_hidden1 @ X.T               
    grad_bias_hidden1   = delta_hidden1.copy()              

    return (grad_weight_hidden1, grad_bias_hidden1,grad_weight_hidden2, grad_bias_hidden2,grad_weight_output,  grad_bias_output)

## 5. Running Forward & Backward Pass

In [89]:
# Forward Pass                                               
(Z_h1_data1, A_h1_data1, Z_h2_data1, A_h2_data1,Z_out_data1, y_pred_data1) = forward_pass(X_data1,weight_hidden1, bias_hidden1,weight_hidden2, bias_hidden2,weight_output,  bias_output)
(Z_h1_data2, A_h1_data2, Z_h2_data2, A_h2_data2,Z_out_data2, y_pred_data2) = forward_pass(X_data2,weight_hidden1, bias_hidden1,weight_hidden2, bias_hidden2,weight_output,  bias_output)

# Loss (MSE)                                                 
mse_loss = 0.5 * ((y_pred_data1 - y_data1)**2 + (y_pred_data2 - y_data2)**2)

# Backward Pass                                              
(grad_wh1_data1, grad_bh1_data1,grad_wh2_data1, grad_bh2_data1,grad_wo_data1,  grad_bo_data1) = backward_pass(X_data1, y_data1,weight_hidden2, weight_output,Z_h1_data1, A_h1_data1, Z_h2_data1, A_h2_data1,y_pred_data1)
(grad_wh1_data2, grad_bh1_data2,grad_wh2_data2, grad_bh2_data2,grad_wo_data2,  grad_bo_data2) = backward_pass(X_data2, y_data2,weight_hidden2, weight_output,Z_h1_data2, A_h1_data2, Z_h2_data2, A_h2_data2,y_pred_data2)

## 6. Rata-rata Gradien & Update Bobot

In [90]:
# Rata-rata gradien (N = 2 data)                             
avg_grad_weight_output  = 0.5*(grad_wo_data1  + grad_wo_data2)
avg_grad_bias_output    = 0.5*(grad_bo_data1  + grad_bo_data2)

avg_grad_weight_hidden2 = 0.5*(grad_wh2_data1 + grad_wh2_data2)
avg_grad_bias_hidden2   = 0.5*(grad_bh2_data1 + grad_bh2_data2)

avg_grad_weight_hidden1 = 0.5*(grad_wh1_data1 + grad_wh1_data2)
avg_grad_bias_hidden1   = 0.5*(grad_bh1_data1 + grad_bh1_data2)

# Update bobot: θ_baru = θ_lama − α · ∇θ                    
weight_output_new  = weight_output  - learning_rate * avg_grad_weight_output
bias_output_new    = bias_output    - learning_rate * avg_grad_bias_output

weight_hidden2_new = weight_hidden2 - learning_rate * avg_grad_weight_hidden2
bias_hidden2_new   = bias_hidden2   - learning_rate * avg_grad_bias_hidden2

weight_hidden1_new = weight_hidden1 - learning_rate * avg_grad_weight_hidden1
bias_hidden1_new   = bias_hidden1   - learning_rate * avg_grad_bias_hidden1

## 7. Tampilkan Semua Hasil

In [91]:
# Forward Pass                                             
print(f"\nFORWARD PASS")
print(f"  Data 1  |  X = [1, -2]   |  y = 1  →  ŷ₁ = {y_pred_data1:.4f}")
print(f"  Data 2  |  X = [-1, 1]   |  y = 4  →  ŷ₂ = {y_pred_data2:.4f}")
print(f"\n  MSE Loss = {mse_loss:.4f}")

# Gradien Data 1                                          
print(f"\nGRADIEN DATA 1  (X=[1,-2], y=1)")
print(f"  δ_output₁  (error output)    = {y_pred_data1 - y_data1:.4f}")
print(f"  ∂L/∂W_output₁                = {grad_wo_data1}")
print(f"  ∂L/∂b_output₁                = {grad_bo_data1:.4f}")
print(f"  δ_hidden2₁ (error H2)        = {grad_bh2_data1.T}")
print(f"  ∂L/∂W_hidden2₁ =\n{grad_wh2_data1}")
print(f"  δ_hidden1₁ (error H1)        = {grad_bh1_data1.T}")
print(f"  ∂L/∂W_hidden1₁ =\n{grad_wh1_data1}")

# Gradien Data 2                                          
print(f"\nGRADIEN DATA 2  (X=[-1,1], y=4)")
print(f"  δ_output₂  (error output)    = {y_pred_data2 - y_data2:.4f}")
print(f"  ∂L/∂W_output₂                = {grad_wo_data2}")
print(f"  ∂L/∂b_output₂                = {grad_bo_data2:.4f}")
print(f"  δ_hidden2₂ (error H2)        = {grad_bh2_data2.T}")
print(f"  ∂L/∂W_hidden2₂ =\n{grad_wh2_data2}")
print(f"  δ_hidden1₂ (error H1)        = {grad_bh1_data2.T}")
print(f"  ∂L/∂W_hidden1₂ =\n{grad_wh1_data2}")

# Rata-Rata Gradien                                       
print(f"\nRATA-RATA GRADIEN  (avg atas 2 data)")
print(f"  ∇W_output  = {avg_grad_weight_output}")
print(f"  ∇b_output  = {avg_grad_bias_output:.4f}")
print(f"  ∇W_hidden2 =\n{avg_grad_weight_hidden2}")
print(f"  ∇b_hidden2 = {avg_grad_bias_hidden2.T}")
print(f"  ∇W_hidden1 =\n{avg_grad_weight_hidden1}")
print(f"  ∇b_hidden1 = {avg_grad_bias_hidden1.T}")

# Bobot Baru                                           
print(f"\nBOBOT BARU  (setelah 1 iterasi, α={learning_rate})")
print(f"  weight_output_new   = {weight_output_new}")
print(f"  bias_output_new     = {bias_output_new}")
print(f"\n  weight_hidden2_new =\n{weight_hidden2_new}")
print(f"  bias_hidden2_new    = {bias_hidden2_new.T}")
print(f"\n  weight_hidden1_new =\n{weight_hidden1_new}")
print(f"  bias_hidden1_new    = {bias_hidden1_new.T}")


FORWARD PASS
  Data 1  |  X = [1, -2]   |  y = 1  →  ŷ₁ = -3.0000
  Data 2  |  X = [-1, 1]   |  y = 4  →  ŷ₂ = 2.0000

  MSE Loss = 10.0000

GRADIEN DATA 1  (X=[1,-2], y=1)
  δ_output₁  (error output)    = -4.0000
  ∂L/∂W_output₁                = [[-8. -0.]]
  ∂L/∂b_output₁                = -4.0000
  δ_hidden2₁ (error H2)        = [[ 8. -0.]]
  ∂L/∂W_hidden2₁ =
[[ 8. 32. 32.]
 [ 0.  0.  0.]]
  δ_hidden1₁ (error H1)        = [[  8. -16.  16.]]
  ∂L/∂W_hidden1₁ =
[[  8. -16.]
 [-16.  32.]
 [ 16. -32.]]

GRADIEN DATA 2  (X=[-1,1], y=4)
  δ_output₂  (error output)    = -2.0000
  ∂L/∂W_output₂                = [[-2. -2.]]
  ∂L/∂b_output₂                = -2.0000
  δ_hidden2₂ (error H2)        = [[ 4. -6.]]
  ∂L/∂W_hidden2₂ =
[[0. 0. 0.]
 [0. 0. 0.]]
  δ_hidden1₂ (error H1)        = [[-0. -0.  0.]]
  ∂L/∂W_hidden1₂ =
[[0. 0.]
 [0. 0.]
 [0. 0.]]

RATA-RATA GRADIEN  (avg atas 2 data)
  ∇W_output  = [[-5. -1.]]
  ∇b_output  = -3.0000
  ∇W_hidden2 =
[[ 4. 16. 16.]
 [ 0.  0.  0.]]
  ∇b_hidden2 =